export const SIDEBAR_ITEMS = [
  {
    title: "Dashboard",
    icon: "ri:dashboard-fill",
    name: "dashboard",
    path: "/",
  },
  {
    title: "Users",
    icon: "mdi:person",
    name: "users",
    path: "/users",
  },
  {
    title: "Activity Feeds",
    icon: "mingcute:time-fill",
    name: "activity-feeds",
    path: "/activity-feeds",
  },
  {
    title: "Today`s Report",
    icon: "mdi:report-multiple",
    name: "todays-report",
    path: "/daily-report",
  },
  {
    title: "Daily reports",
    icon: "mdi:report-multiple",
    name: "daily-reports",
    path: "/daily-reports",
  },
  {
    title: "My Projects",
    icon: "ant-design:project-filled",
    name: "my-projects",
    path: "/my-projects",
  },
  {
    title: "Projects",
    icon: "ant-design:project-filled",
    name: "projects",
    path: "/projects",
  },
  {
    title: "My Requests",
    icon: "mdi:invoice-text-edit",
    name: "my-requests",
    path: "/my-requests",
  },
  {
    title: "Requests",
    icon: "mdi:invoice-text-edit",
    name: "requests",
    path: "/requests",
  },
  {
    title: "My Reports",
    icon: "iconamoon:invoice-fill",
    name: "my-reports",
    path: "/my-reports",
  },
  {
    title: "Skills",
    icon: "ic:baseline-laptop",
    name: "skills",
    path: "/skills",
  },
  {
    title: "HR Annoucements",
    icon: "raphael:speaker",
    name: "hr-annoucements",
    path: "/hr-annoucements",
  },
  {
    title: "Public Holidays",
    icon: "ic:outline-holiday-village",
    name: "Public Holidays",
    path: "/public-holidays",
  },
];

export const PROTECTED_ROUTES = [
  "/",
  "/users",
  "/users/add-user",
  "/activity-feeds",
  "/user",
  "/settings",
  "/projects",
  "/my-projects",
  "/project",
  "/daily-report",
  "/report",
  "/daily-reports",
  "/public-holidays",
  "/analytics",
  "/my-requests",
  "/requests",
];
