export const users = [
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: true,
  },
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: false,
  },
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: true,
  },
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: true,
  },
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: false,
  },
  {
    emp_id: 123,
    name: "Test user",
    email: "test.user@gmail.com",
    att_id: 12,
    department: "software development",
    designation: "associate software engineer",
    position: "front end developer",
    profile_picture: "",
    active: true,
  },
];
